name: Build Standalone Timer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build Windows executable
      run: |
        cd fyne-app/standalone-app
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -H=windowsgui" -o ../../seekbar-timer-windows.exe .
        
    - name: Build Linux executable  
      run: |
        cd fyne-app/standalone-app
        GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o ../../seekbar-timer-linux .
        
    - name: Build macOS executable
      run: |
        cd fyne-app/standalone-app
        GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o ../../seekbar-timer-macos .
        
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: seekbar-timer-windows.exe
        retention-days: 7
        
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: seekbar-timer-linux
        retention-days: 7
        
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: seekbar-timer-macos
        retention-days: 7