name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wpf
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore RemainingTimeMeter.csproj
      
    - name: Build
      run: dotnet build RemainingTimeMeter.csproj --no-restore --configuration Release
      
    - name: Check code style
      run: dotnet format style RemainingTimeMeter.csproj --verify-no-changes --verbosity normal
      
    - name: Check analyzers
      run: dotnet format analyzers RemainingTimeMeter.csproj --verify-no-changes --verbosity normal
      
    - name: Run tests (if any)
      run: dotnet test RemainingTimeMeter.csproj --no-build --configuration Release --verbosity normal
      continue-on-error: true  # Continue even if no tests are found