name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wpf

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore RemainingTimeMeter.csproj

      - name: Build
        run: dotnet build RemainingTimeMeter.csproj --no-restore --configuration Release

      - name: Setup Node.js (for prettier)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install prettier
        run: npm install -g prettier

      - name: Check formatting (all files)
        run: make format-check

      - name: Check code style & analyzers
        run: |
          dotnet format style RemainingTimeMeter.csproj --verify-no-changes --verbosity normal
          dotnet format analyzers RemainingTimeMeter.csproj --verify-no-changes --verbosity normal

      - name: Run tests
        run: dotnet test ../tests/RemainingTimeMeter.Tests.csproj --configuration Release --verbosity normal
