name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get version from tag
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Generate release notes
      id: release_notes
      run: |
        # Get commits since last tag
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        
        if [ -z "$PREVIOUS_TAG" ]; then
          echo "No previous tag found, including all commits"
          COMMITS=$(git log --pretty=format:"- %s (%h)" --reverse)
        else
          echo "Previous tag: $PREVIOUS_TAG"
          COMMITS=$(git log --pretty=format:"- %s (%h)" --reverse $PREVIOUS_TAG..HEAD)
        fi
        
        # Create release notes
        cat > release_notes.md << EOF
        ## RemMeter v${{ steps.get_version.outputs.version }}
        
        ### Changes in this release:
        
        $COMMITS
        
        ### Installation
        
        Download the appropriate version for your system:
        
        #### 🎯 Framework-dependent (Recommended - Smaller size)
        - **RemMeter-${{ steps.get_version.outputs.version }}-framework-dependent-win-x64.exe** - 64-bit Windows
        - **RemMeter-${{ steps.get_version.outputs.version }}-framework-dependent-win-x86.exe** - 32-bit Windows
        
        ⚠️ **Requires**: .NET 8.0 Desktop Runtime ([Download](https://dotnet.microsoft.com/download/dotnet/8.0))
        
        #### 🔧 Self-contained (Larger size - No runtime required)
        - **RemMeter-${{ steps.get_version.outputs.version }}-self-contained-win-x64.exe** - 64-bit Windows
        - **RemMeter-${{ steps.get_version.outputs.version }}-self-contained-win-x86.exe** - 32-bit Windows
        
        ### Full Changelog
        
        https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...v${{ steps.get_version.outputs.version }}
        EOF
        
        echo "release_notes_file=release_notes.md" >> $GITHUB_OUTPUT
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: RemMeter v${{ steps.get_version.outputs.version }}
        body_path: ${{ steps.release_notes.outputs.release_notes_file }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}